version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    # restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mtips5s_db
      - MYSQL_ROOT_PASSWORD=secret
    volumes: 
      - dbdata-mtips5s:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --max_allowed_packet=134217728'
    networks:
      - app-network-mtips5s

  webserver:
    platform: linux/amd64
    image: nginx:latest
    container_name: webserver
    # restart: unless-stopped

    ports:
      # - "8081:80"
      - "80:80"
      - "443:443"
    volumes:
      - ./volume/nginx/nginx:/etc/nginx/nginx.d/:rw
      - ./volume/nginx/conf/:/etc/nginx/conf.d/:rw
      - ./volume/nginx/html/:/usr/share/nginx/html:rw
      - ./volume/certbot/www/:/var/www/certbot/:rw
      - ./volume/certbot/conf/:/etc/nginx/ssl/:rw
    networks:
      - app-network-mtips5s
    
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network-mtips5s
  
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    # restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - MAX_EXECUTION_TIME=1200
      - MEMORY_LIMIT=1512M
      - UPLOAD_LIMIT=2580M
    volumes: 
      - dbdata-mtips5s:/var/lib/mysql
    networks:
      - app-network-mtips5s
  
  # cron:
  #   platform: linux/amd64
  #   image: khuong123/mtips5s_cron:dev_1
  #   container_name: mtips5s_cron
  #   networks:
  #     - app-network-mtips5s

  # discord:
  #   platform: linux/amd64
  #   image: khuong123/mtips5s_discord:dev_1
  #   env_file: .env
  #   container_name: mtips5s_discord
  #   networks:
  #     - app-network-mtips5s

  mtips5s_web:
    platform: linux/amd64
    # restart: on-failure
    # image: python:3.9
    image: tesseractproject/tesseract
    container_name: mtips5s_web
    env_file: .cicd_env
    working_dir: /app
    build: .
    # command: >
    #   /bin/sh -c "pip install --no-cache-dir -r requirements.txt&&apt-get update && apt-get install ffmpeg libsm6 libxext6  -y"
    volumes:
      # - ./utils/traineddata/:/usr/share/tesseract-ocr/5/tessdata/
      # - ./templates/assets/:/app/templates/assets/
      - ./:/app
      
    # environment:
    #   - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:secret@db:3306/my_hikari
    environment:
      DB_HOST: db:3306
      DB_NAME: my_hikari
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "8000:8000"
    networks:
      - app-network-mtips5s

  

volumes:
  dbdata-mtips5s:
  redis_data:
    driver: local


networks:
  app-network-mtips5s:
    driver: bridge